#!/bin/sh
# =============================================================================
# Unitex/GramLab Unix-like Environments Setup Script
# https://github.com/UnitexGramLab/unitex-packaging-unix
# =============================================================================
# Copyright (C) 2015 Université Paris-Est Marne-la-Vallée <unitex@univ-mlv.fr>
# 
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.
# 
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
# 
# You should have received a copy of the GNU Lesser General Public
# License along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA.
#
# cristian.martinez@univ-paris-est.fr (martinec)
# 
# =============================================================================
# This shell script must work in any POSIX-like system, including systems without 
# bash. See this helpful document on writing portable shell scripts:
# @see http://www.gnu.org/s/hello/manual/autoconf/Portable-Shell.html
# =============================================================================
# Script code must be ShellCheck-compliant for information about how to run 
# ShellCheck locally @see http://www.shellcheck.net/about.html
# e.g shellcheck -s sh jar-launch
# =============================================================================
# Constants
# =============================================================================
UNITEX_JAR_LAUNCH_SCRIPT_NAME=$(basename -- "$0")
# =============================================================================
# Script working directory
# =============================================================================
# Working directory snippet from @source http://stackoverflow.com/a/17744637/2042871
UNITEX_JAR_LAUNCH_SCRIPT=$(cd -P -- "$(dirname -- "$0")" && pwd -P) &&\
UNITEX_JAR_LAUNCH_SCRIPT="$UNITEX_JAR_LAUNCH_SCRIPT/$UNITEX_JAR_LAUNCH_SCRIPT_NAME)"

# Resolve symlinks snippet from @source http://stackoverflow.com/a/697552/2042871
while [ -h "$UNITEX_JAR_LAUNCH_SCRIPT" ]; do
    UNITEX_JAR_LAUNCH_DIR=$(dirname -- "$UNITEX_JAR_LAUNCH_SCRIPT")
    UNITEX_JAR_LAUNCH_SYM=$(readlink   "$UNITEX_JAR_LAUNCH_SCRIPT")
    UNITEX_JAR_LAUNCH_SCRIPT="$(cd "$UNITEX_JAR_LAUNCH_DIR"  &&\
                                  cd "$(dirname  -- "$UNITEX_JAR_LAUNCH_SYM")" &&\
                                 pwd)/$(basename -- "$UNITEX_JAR_LAUNCH_SYM")"
done  # [ -h "$UNITEX_JAR_LAUNCH_SCRIPT" ]

# Set-up working directory 
UNITEX_JAR_LAUNCH_BASEDIR="$(dirname  -- "$UNITEX_JAR_LAUNCH_SCRIPT")"

# =============================================================================
# Load dependencies
# =============================================================================
. "$UNITEX_JAR_LAUNCH_BASEDIR/platform"

# =============================================================================
# Print usage message
# =============================================================================
usage() {
    echo "Usage:"
    echo "  $UNITEX_JAR_LAUNCH_SCRIPT_NAME JAR_FILE [JAVA_OPTIONS...]"
    echo "Options:"
    echo "  -v|--verbosity=N  : manually set the verbosity level 0...7"
    exit 1
}  # usage()

# =============================================================================
# Java not found message
# =============================================================================
unitex_jar_launch_java_not_found_message() {
  if [ ! -n "${UNITEX_SETUP_JAVA_VENDOR+1}" ]; then
    echo "$UNITEX_SETUP_LINE_STRING"
    echo "WARNING: In order to run $UNITEX_JAR_LAUNCH_FILE_NAME, you need Java version $UNITEX_SETUP_MINIMAL_JAVA_VERSION_STRING"
    echo "or later installed on your system. To download Java online, please go to"
    echo "$UNITEX_SETUP_JAVA_DOWNLOAD_URL"
    echo "$UNITEX_SETUP_LINE_STRING"
    $UNITEX_SETUP_COMMAND_OPEN_URL "$UNITEX_SETUP_JAVA_DOWNLOAD_URL" > /dev/null 2>&1 
    exit 1;
  fi  
}

# =============================================================================
# Java classpath
# =============================================================================
unitex_jar_launch_setup_classpath() {
	# add CLASSPATH
  if [ -n "${CLASSPATH+1}" ]; then
  	UNITEX_JAR_LAUNCH_CLASSPATH="$UNITEX_JAR_LAUNCH_CLASSPATH:$CLASSPATH"
  fi

  # add main jar
  UNITEX_JAR_LAUNCH_CLASSPATH="$UNITEX_JAR_LAUNCH_CLASSPATH:$UNITEX_JAR_LAUNCH_FILE_BASEDIR/$UNITEX_JAR_LAUNCH_FILE_NAME"

  # add UNITEX_JAR_LAUNCH_FILE_BASEDIR/classes/*
  if [ -d "$UNITEX_JAR_LAUNCH_FILE_BASEDIR/classes" ]; then
    UNITEX_JAR_LAUNCH_CLASSPATH="$UNITEX_JAR_LAUNCH_CLASSPATH:$UNITEX_JAR_LAUNCH_FILE_BASEDIR/classes/*"
  fi	

  # add UNITEX_JAR_LAUNCH_FILE_BASEDIR/lib/*
  if [ -d "$UNITEX_JAR_LAUNCH_FILE_BASEDIR/lib" ]; then
    UNITEX_JAR_LAUNCH_CLASSPATH="$UNITEX_JAR_LAUNCH_CLASSPATH:$UNITEX_JAR_LAUNCH_FILE_BASEDIR/lib/*"
  fi

  # Detect OS
  unitex_setup_os_type_detection

  # OSTYPE (re)defined by unitex_setup_os_type_detection
  # shellcheck disable=SC2039
  local -r UNITEX_SETUP_OS_IS_CYGWIN=$(case "$OSTYPE" in
    (*cygwin*)   echo "1";;
    (*)          echo "0";;
  esac)

  # Running Java from Cygwin
  # @http://stackoverflow.com/a/16538153/2042871
	if [ "$UNITEX_SETUP_OS_IS_CYGWIN" -ne 0 ]; then
		UNITEX_JAR_LAUNCH_CLASSPATH=$(cygpath -mp "$UNITEX_JAR_LAUNCH_CLASSPATH")
	fi
}  

# =============================================================================
# Command line check
# =============================================================================
if [ $# -lt 1 ]
then
   echo "./$UNITEX_JAR_LAUNCH_SCRIPT_NAME: wrong arguments"
   usage
fi

# =============================================================================
# Arguments
# =============================================================================
# jar file
UNITEX_JAR_LAUNCH_FILE="$1"
shift

# extra parameters
UNITEX_JAR_LAUNCH_OPTIONS="$*"

# =============================================================================
# Get jar filename
# =============================================================================
UNITEX_JAR_LAUNCH_FILE_NAME=$(basename -- "$UNITEX_JAR_LAUNCH_FILE")

# =============================================================================
# Try to resolve the absolute path of the jar file
# =============================================================================
# Resolve symlinks snippet from @source http://stackoverflow.com/a/697552/2042871
while [ -h "$UNITEX_JAR_LAUNCH_FILE" ]; do
    UNITEX_JAR_LAUNCH_FILE_DIR=$(dirname -- "$UNITEX_JAR_LAUNCH_FILE")
    UNITEX_JAR_LAUNCH_FILE_SYM=$(readlink   "$UNITEX_JAR_LAUNCH_FILE")
    UNITEX_JAR_LAUNCH_FILE="$(cd "$UNITEX_JAR_LAUNCH_FILE_DIR"  &&\
                                  cd "$(dirname  -- "$UNITEX_JAR_LAUNCH_FILE_SYM")" &&\
                                 pwd)/$(basename -- "$UNITEX_JAR_LAUNCH_FILE_SYM")"
done  # [ -h "$UNITEX_JAR_LAUNCH_FILE" ]

# Set-up working directory 
UNITEX_JAR_LAUNCH_FILE_BASEDIR="$(dirname  -- "$UNITEX_JAR_LAUNCH_FILE")"

# =============================================================================
# Main
# =============================================================================
unitex_setup_java_detection
unitex_jar_launch_java_not_found_message
unitex_jar_launch_setup_classpath

# =============================================================================
# Launch jar
# =============================================================================
cd "$UNITEX_JAR_LAUNCH_FILE_BASEDIR"

# shellcheck disable=SC2086
$UNITEX_SETUP_COMMAND_JAVA $UNITEX_JAR_LAUNCH_OPTIONS\
                           -cp  "$UNITEX_JAR_LAUNCH_CLASSPATH"\
                           -jar "$UNITEX_JAR_LAUNCH_FILE"